export const categories = [
  { value: "mobile", label: "Mobile phones and accessories" },
  { value: "laptop", label: "Laptops and accessories" },
  { value: "tablet", label: "Tablets and accessories" },
  { value: "camera", label: "Cameras and photography" },
  { value: "tv", label: "Televisions and entertainment systems" },
  { value: "audio", label: "Headphones, speakers and audio devices" },
  { value: "gaming", label: "Gaming consoles and accessories" },
  { value: "appliances", label: "Home appliances" },
  { value: "fashion_men", label: "Men's fashion" },
  { value: "fashion_women", label: "Women's fashion" },
  { value: "fashion_kids", label: "Kids' fashion" },
  { value: "footwear", label: "Footwear" },
  { value: "beauty", label: "Beauty and personal care" },
  { value: "health", label: "Health and wellness products" },
  { value: "furniture", label: "Furniture and home decor" },
  { value: "kitchen", label: "Kitchen and dining" },
  { value: "books", label: "Books and stationery" },
  { value: "sports", label: "Sports and fitness" },
  { value: "automotive", label: "Automotive accessories" },
  { value: "toys", label: "Toys and games" },
];
